name: qemu
on: [push]

env:
  builder: builder-3
  ref: ref-3

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Mark builder
        run: echo "${{ env.builder }}" > builder.txt
      
      - name: Mark ref
        run: echo "${{ env.ref }}" > ref.txt
      
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          tag_name: qemu-${{ env.ref }}
          files: |
            ${{ github.workspace }}/builder.txt
            ${{ github.workspace }}/ref.txt
