name: linux-kernel
on: [push]

env:
  builder: ghcr.io/rikonor/linux-kernel-builder:06601067dded0f4e1fed2527bfb99b0f19f19274
  ref: ref-1

jobs:
  linux-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Login to container registry
        run: |
          docker login \
            -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} \
            -p ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} \
            ghcr.io

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          tag_name: linux-kernel-${{ env.ref }}
          body: |
            Builder: ${{ env.builder }}
            Upstream Ref: ${{ env.ref }}
